### PR TITLE
Several additions: endDate view option, 'draw-end' event, removeAllSelected() method, caption changes, & 'k-blackout' class 

### PR DESCRIPTION
**Pull request by coreyzev**
First off, this has as lot of changes (though mostly very simple) in one request. I did not test extensively. But I have been working in Chrome & IE9. So far, so good. 

Feel free to take bits and pieces of this.

I made sure to break it up into commits for each feature. So you can see each one on its own. (Aside from the last commit, which was a bit of an afterthought).

In more detail:

* fixed variables - f17ab6b - for some reason both variables for disable next were `disableNext` sans the declaration. So I added Month and Year respectively
* Month Caption adjustments - d973408 - I changed the title span to a div, and placed the month and year in their own divs so they can be styled on their own if needed. (e.g. http://i.imgur.com/y0yK34I.png )
* removeAllSelected() - 8ac3047 - I needed this in my own code, and I figured I'd be doing it more than once, so I just wrote a method and added it in. 
* 'draw-end' event - 120b579 - I needed to do more jQuery styling after a draw had finished and I had no way of knowing without relying on a combination of "view-changed" and "change", and even then there were still gaps. 
* 'k-blackout' class - 35f21cc - because sometimes you want to style blacked out dates differently than inactive dates
* endDate option - 2955464 - I had a situation where I need to limit not just the direction the calendar starts in, but also where it ends. And so I added this to control that. Following all the patterns set out by previous day selection options.

* The last 3 commits are just updating the readme, fixing the css for the title, and fixing a bug #2697 that I realized due to moment

thanks for making such a great, agnostic, datepicker! I'm really enjoying using it. And modifying it.

### CODE REVIEW

**Comment by coreyzev** [comment]
I am working with Kalendae again for the first time since last year, and I will need some of these changes again. 

Obviously I will need to fix the conflicts, but is there anything else in particular that kept you from either refusing or accepting this pull request?

**Comment by ChiperSoft** [comment]
I don't remember seeing this PR before, so I think I just somehow overlooked it. The changes look reasonable, if you can address the conflicts then I'll merge it.

**Comment by ChiperSoft** [comment]
Since there's a lot of new features in this PR, could you also update the changelog with everything it adds, under the In Development heading.

**Comment by coreyzev** [comment]
Conflicts fixed, need to update the changelog

**Comment by coreyzev** [comment]
Okay. That was so much rebasing... but it's done. 

Thanks!

**Comment by ChiperSoft** [comment]
Rocking. Will try to wrap up a release this weekend.

**Comment by coreyzev** [comment]
I just realized I forgot to add the the changelog the new class `k-blackout`.

**Pull request merged**
