### PR TITLE
Make day header clickable.

### PR DESCRIPTION
**Pull request by erickjth**
Make day header clickable. Add support to select all days in a column inside a month when user selects the day on the header.

### CODE REVIEW

**Comment by ChiperSoft** [comment]
This sounds like an excellent addition. I want to check it out before I merge it, will try to get that today.

In the mean time can you please put those trailing spaces back into the readme? They were there on purpose, that's how you do a carriage return in markdown.

**Comment by ChiperSoft** [comment]
Got a chance to look at it. Excellent addition, thanks for this.

**Comment by erickjth** [comment]
Glad to know you like that feature. You're welcome.

**Comment by ChiperSoft** [comment]
This is now released in version 0.6

**Pull request merged**
