### PR TITLE
month should be initialized with the first day of the month

### PR DESCRIPTION
**Pull request by IlanFrumer**

### CODE REVIEW

**Comment by ChiperSoft** [comment]
Worthwhile change.

Are you seeing this actually break something? The only places month gets used are to retrieve the actual month, so it shouldn't really matter.

**Comment by IlanFrumer** [comment]
@ChiperSoft Actually the users of our system found this bug.

The next month button was getting disabled on 'today-past' mode even though it still has one month ahead.

**Comment by ChiperSoft** [comment]
Ah, I think somebody had reported that bug a long time ago but I couldn't reproduce it.

Thank you!

**Comment by ChiperSoft** [comment]
0.6.1 is published with this fix.

**Pull request merged**
