### PR TITLE
getTodayYearDate dynamic function

### LINKED ISSUE #165: today private variable should not be static
When the date changes (at midnight) it won't update. This is because it only gets initialized once.

Source: https://github.com/ChiperSoft/Kalendae/blob/master/src/moment.ext.js#L19
```
today = Kalendae.moment().startOf('day');
```

### PR DESCRIPTION
**Pull request by IlanFrumer**
following PR #166 fixes #165

### CODE REVIEW

**Comment by Florian-R** [comment]
@ChiperSoft Just to be sure, do you plan no merge this one? Thanks!

**Comment by ChiperSoft** [comment]
done

**Comment by Florian-R** [comment]
Wow that was quick. Thanks a lot!

**Comment by ChiperSoft** [comment]
You just happened to hit me when I wasn't otherwise busy :)

**Comment by IlanFrumer** [comment]
@ChiperSoft Are you pushing a version with this change soon ?

**Comment by ChiperSoft** [comment]
I'll try to cut a new version this week, as I'd like to get #176 released as well, but I can't make any promises.

**Comment by ChiperSoft** [comment]
This is now released in version 0.6

**Pull request merged**
